[versions]
lombok = '1.18.24'
jb-annotation = '23.1.0'

[libraries]
lombok = { module = 'org.projectlombok:lombok', version.ref = 'lombok' }
jetbrains-annotations = { module = 'org.jetbrains:annotations', version.ref = 'jb-annotation' }

[bundles]